/**
 * Email Service Integration Example
 * 
 * This example shows how to send emails using SendGrid
 * Can be adapted for other email providers (Mailgun, AWS SES, etc.)
 */

const sgMail = require('@sendgrid/mail');

class EmailService {
  constructor() {
    const apiKey = process.env.EMAIL_API_KEY;
    if (apiKey) {
      sgMail.setApiKey(apiKey);
    }
  }

  async sendEmail({ to, subject, text, html }) {
    const msg = {
      to: to,
      from: 'a1@j7.no', // Your verified sender
      subject: subject,
      text: text,
      html: html
    };

    try {
      const response = await sgMail.send(msg);
      console.log('Email sent successfully:', response[0].statusCode);
      return { success: true, response };
    } catch (error) {
      console.error('Error sending email:', error);
      if (error.response) {
        console.error(error.response.body);
      }
      return { success: false, error };
    }
  }

  async sendWelcomeEmail(recipientEmail, recipientName) {
    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; }
            .container { max-width: 600px; margin: 0 auto; padding: 20px; }
            .header { background: linear-gradient(135deg, #6366f1, #ec4899); color: white; padding: 20px; text-align: center; }
            .content { padding: 20px; }
            .footer { text-align: center; padding: 20px; color: #666; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>Welcome to A1.j7.no</h1>
            </div>
            <div class="content">
              <p>Hello ${recipientName},</p>
              <p>Welcome to A1.j7.no, the autonomous AI-powered website!</p>
              <p>We're excited to have you here. This message was automatically generated by our autonomous system.</p>
              <p>Visit us at: <a href="https://a1.j7.no">https://a1.j7.no</a></p>
            </div>
            <div class="footer">
              <p>&copy; 2026 A1.j7.no - An Autonomous AI Project</p>
            </div>
          </div>
        </body>
      </html>
    `;

    return await this.sendEmail({
      to: recipientEmail,
      subject: 'Welcome to A1.j7.no - Autonomous Website',
      text: `Hello ${recipientName}, Welcome to A1.j7.no!`,
      html: html
    });
  }

  async sendUpdateNotification(message) {
    return await this.sendEmail({
      to: 'a1@j7.no',
      subject: 'Autonomous Update Notification',
      text: message,
      html: `<p>${message}</p>`
    });
  }
}

module.exports = EmailService;

// Usage example:
// const emailService = new EmailService();
// await emailService.sendWelcomeEmail('user@example.com', 'John Doe');
// await emailService.sendUpdateNotification('New content published!');
